### ISSUE TITLE
found duplicate series

### ISSUE THREAD

**Issue by oktavianabd** [andrii29/mongodb-profiler-exporter#7]
i'm getting this error on grafana dashboard "slow queries panel" both query A & B
would you please suggest?

execution: found duplicate series for the match group {ns="nytaxi.nyGreenTaxi", query_hash="8880B5AF"} on the right hand-side of the operation: [{db="nytaxi", instance="10.63.20.14:9179", job="mongodb-profiler", ns="nytaxi.nyGreenTaxi", op="command", query_framework="classic", query_hash="8880B5AF", query_shape="{'explain': {'find': '?', 'filter': {}, 'skip': '?', 'maxTimeMS': '?'}, 'verbosity': '?'}"}, {db="nytaxi", instance="10.63.20.14:9179", job="mongodb-profiler", ns="nytaxi.nyGreenTaxi", op="command", plan_summary="COUNT_SCAN { _id: 1 }", query_framework="classic", query_hash="8880B5AF", query_shape="{'aggregate': '?', 'pipeline': [{'$match': {}}, {'$count': '?'}], 'hint': '?', 'maxTimeMS': '?'}"}];many-to-many matching not allowed: matching labels must be unique on one side

query A
![image](https://github.com/andrii29/mongodb-profiler-exporter/assets/13726700/47a96b0f-6430-45db-8835-ae2870aadfda)
query B
![image](https://github.com/andrii29/mongodb-profiler-exporter/assets/13726700/db1d09ee-e163-4e52-b01c-ceee1a7dad38)

**Comment by andrii29** [comment]
try [1.8](https://github.com/andrii29/mongodb-profiler-exporter/releases/tag/1.8) or [docker](https://hub.docker.com/layers/andriik/mongodb-profiler-exporter/1.8/images/sha256-17d9da1a368010cb8e824dfe4a26f947cc2a5dea74887e5511aeca28a1ecc1f7?context=explore)

**Comment by oktavianabd** [comment]
thanks a lot it works now
